[build]
  command = "CI='' npm run build"
  publish = "/build"
  base ="/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200
  force = true 